apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        cpu: 10
---
  apiVersion: v1
  kind: Pod
  metadata:
    name: nginx-2
    labels:
      app: nginx-2
  spec:
    containers:
    - image: nginx
      name: nginx
    - image: linuxserver/openssh-server
      name: mgmt
    - image: balabit/syslog-ng
      name: logging
---
  apiVersion: v1
  kind: ReplicationController
  metadata:
    name: nginx
  spec:
    replicas: 3
    selector:
      app: nginx
    template:
      metadata:
        name: nginx
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
---
  apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    name: nginx
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        name: nginx
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nginx
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        name: nginx
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: green
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: green
    template:
      metadata:
        labels:
          app: green
      spec:
        containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: blue
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: blue
    template:
      metadata:
        labels:
          app: blue
      spec:
        containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
---
  apiVersion: v1
  kind: Service
  metadata:
    name: green-svc
    labels:
      app: green
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
    selector:
      app: green
    type: ClusterIP
---
  apiVersion: v1
  kind: Service
  metadata:
    name: blue-svc
    labels:
      app: blue
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
    selector:
      app: blue
    type: NodePort
---
  apiVersion: v1
  kind: Service
  metadata:
    name: blue-svc
    labels:
      app: blue
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
    selector:
      app: blue
    type: LoadBalancer